# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designers', '0004_designers_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designers',
            name='address',
            field=models.TextField(max_length=500),
        ),
    ]
